name: Feature request
description: Suggest an improvement
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: proposal
    attributes:
      label: What would you like to change?
      description: Explain the problem and proposed solution.
    validations:
      required: true
